name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "2b7a52c9-cc1a-45f3-8403-6b515cdf303e"      # 替换为你创建的数据库 ID
